version: "3"

services:
  main:
    build:
      context: ./main
      dockerfile: Dockerfile
    container_name: main
    restart: always
    env_file: .env
    links:
      - "db:mysqldb"
    depends_on:
      - quant
      - db
    ports:
      - "8080:8080"
    command: sh -c scripts/run.sh

  quant:
    build:
      context: ./quant
      dockerfile: Dockerfile
    container_name: quant
    restart: always
    ports:
      - "9000:9000"
    command: python3 main.py

  db:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: database
    user: "501:20"
    restart: always
    env_file: .env.mysql
    ports:
      - "3306:3306"
    volumes:
      - ./volumes/mysql:/var/lib/mysql
      - ./volumes/seed:/var/lib/mysql-files
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0